name: .NET CI

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.100

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --no-build --runtime win10-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifact-publish
          path: ./publish/*.exe
